// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.CI.Redist")]
[assembly: AssemblyProductAttribute("Plainion.CI")]
[assembly: AssemblyDescriptionAttribute("Plainion.CI")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.7")]
[assembly: AssemblyFileVersionAttribute("1.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.CI.Redist";
        internal const System.String AssemblyProduct = "Plainion.CI";
        internal const System.String AssemblyDescription = "Plainion.CI";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.7";
        internal const System.String AssemblyFileVersion = "1.7";
    }
}
