// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.CI.BuildHost")>]
[<assembly: AssemblyProductAttribute("Plainion.CI")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.CI")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2021")>]
[<assembly: AssemblyVersionAttribute("4.0")>]
[<assembly: AssemblyFileVersionAttribute("4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.CI.BuildHost"
    let [<Literal>] AssemblyProduct = "Plainion.CI"
    let [<Literal>] AssemblyDescription = "Plainion.CI"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2021"
    let [<Literal>] AssemblyVersion = "4.0"
    let [<Literal>] AssemblyFileVersion = "4.0"
