// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.CI.BuildHost")>]
[<assembly: AssemblyProductAttribute("Plainion.CI")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.CI")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2022")>]
[<assembly: AssemblyVersionAttribute("3.2")>]
[<assembly: AssemblyFileVersionAttribute("3.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.CI.BuildHost"
    let [<Literal>] AssemblyProduct = "Plainion.CI"
    let [<Literal>] AssemblyDescription = "Plainion.CI"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2022"
    let [<Literal>] AssemblyVersion = "3.2"
    let [<Literal>] AssemblyFileVersion = "3.2"
