// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.CI.Core")]
[assembly: AssemblyProductAttribute("Plainion.CI")]
[assembly: AssemblyDescriptionAttribute("Plainion.CI")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.2")]
[assembly: AssemblyFileVersionAttribute("1.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.CI.Core";
        internal const System.String AssemblyProduct = "Plainion.CI";
        internal const System.String AssemblyDescription = "Plainion.CI";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.2";
        internal const System.String AssemblyFileVersion = "1.2";
    }
}
