// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.CI.Core")]
[assembly: AssemblyProduct("Plainion.CI")]
[assembly: AssemblyDescription("Plainion.CI")]
[assembly: AssemblyCopyright("Copyright @ 2022")]
[assembly: AssemblyVersion("3.2")]
[assembly: AssemblyFileVersion("3.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.CI.Core";
        internal const System.String AssemblyProduct = "Plainion.CI";
        internal const System.String AssemblyDescription = "Plainion.CI";
        internal const System.String AssemblyCopyright = "Copyright @ 2022";
        internal const System.String AssemblyVersion = "3.2";
        internal const System.String AssemblyFileVersion = "3.2";
    }
}
