// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.CI")]
[assembly: AssemblyProductAttribute("Plainion.CI")]
[assembly: AssemblyDescriptionAttribute("Plainion.CI")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2018")]
[assembly: AssemblyVersionAttribute("1.10")]
[assembly: AssemblyFileVersionAttribute("1.10")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.CI";
        internal const System.String AssemblyProduct = "Plainion.CI";
        internal const System.String AssemblyDescription = "Plainion.CI";
        internal const System.String AssemblyCopyright = "Copyright @ 2018";
        internal const System.String AssemblyVersion = "1.10";
        internal const System.String AssemblyFileVersion = "1.10";
    }
}
