// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.CI")]
[assembly: AssemblyProduct("Plainion.CI")]
[assembly: AssemblyDescription("Plainion.CI")]
[assembly: AssemblyCopyright("Copyright @ 2019")]
[assembly: AssemblyVersion("1.13")]
[assembly: AssemblyFileVersion("1.13")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.CI";
        internal const System.String AssemblyProduct = "Plainion.CI";
        internal const System.String AssemblyDescription = "Plainion.CI";
        internal const System.String AssemblyCopyright = "Copyright @ 2019";
        internal const System.String AssemblyVersion = "1.13";
        internal const System.String AssemblyFileVersion = "1.13";
    }
}
