// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.CI.Tasks")>]
[<assembly: AssemblyProductAttribute("Plainion.CI")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.CI")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2019")>]
[<assembly: AssemblyVersionAttribute("2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.CI.Tasks"
    let [<Literal>] AssemblyProduct = "Plainion.CI"
    let [<Literal>] AssemblyDescription = "Plainion.CI"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2019"
    let [<Literal>] AssemblyVersion = "2.0"
    let [<Literal>] AssemblyFileVersion = "2.0"
