// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.CI.Tasks")>]
[<assembly: AssemblyProductAttribute("Plainion.CI")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.CI")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2018")>]
[<assembly: AssemblyVersionAttribute("1.12")>]
[<assembly: AssemblyFileVersionAttribute("1.12")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.CI.Tasks"
    let [<Literal>] AssemblyProduct = "Plainion.CI"
    let [<Literal>] AssemblyDescription = "Plainion.CI"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2018"
    let [<Literal>] AssemblyVersion = "1.12"
    let [<Literal>] AssemblyFileVersion = "1.12"
